Homework 3
eugene-okulik/Ikonov2024 pull request #4
Opened 2024-07-25 19:31 UTC by iskonov

Добавление ветки homework_3 с файлами в ДЗ № , 25.07,2024

2024-07-26 07:54 UTC, eugene-okulik requested changes
Ура! Файлы есть! Молодец, ты справилась!  
Но нужно починить то, на что ругается Lint. В видео, которое шло к этому занятию, где-то со времени 1 ч 25 мин я рассказываю как разбираться с проблемами, которые возникают на этом этапе.

2024-07-28 16:23 UTC, iskonov commented
Сделалала исправления в файлах ДЗ №3. 28/07/2024

2024-07-28 18:00 UTC, iskonov commented
Сделалала исправления в файлах ДЗ №3. 28/07/2024

2024-07-29 08:13 UTC, eugene-okulik requested changes

2024-07-29 08:13 UTC, eugene-okulik commented on homework/irina_konovalova/homework_3/task_1.py
> +        e = a * b
А почему эти строки не с начала строки, а из середины? Для питона отступы от края строки очень важны. В каких-то ситуациях он вообще не сможет понять что происходит если отступы поставить неправильно. Все строки должны начинаться с начала строки без отступа. Отступы нужны только внутри разных структур: функции, условия, циклы, классы. Но ничего из этого мы еще не изучали.

2024-07-29 08:13 UTC, eugene-okulik commented on homework/irina_konovalova/homework_3/task_1.py
> +        e = a * b
Ну и Lint на это тоже ругается.

2024-07-29 16:11 UTC, iskonov commented on homework/irina_konovalova/homework_3/task_1.py
> +        e = a * b
Здравствуйте Евгений!
Я вроде бы исправила замечания, убрала отступы, сделала команды git add, git commit, git push.
Почему эти изменения не отразились в ветке homework_3?
Может, сделать еще раз?

2024-07-30 07:54 UTC, eugene-okulik approved these changes
Всё отобразилось. Не знаю о чем ты )))

2024-07-30 07:54 UTC, merged

2024-07-30 10:39 UTC, iskonov commented
Я еще все проверила и переделала два раза. 
👍 :)