ДЗ №4, добавила файл dictionary.py
eugene-okulik/Ikonov2024 pull request #5
Opened 2024-08-09 20:15 UTC by iskonov

ДЗ №4, добавила файл 'dictionary.py'. Работа со словарем.

2024-08-10 14:17 UTC, eugene-okulik requested changes
Нужно поправить словарь и наполнить его данными, согласно заданию, поправить в паре мест работу со значениями словаря и исправить все ошибки, которые обнаружил Lint.

2024-08-10 14:17 UTC, eugene-okulik commented on homework/irina_konovalova/homework_4/dictionary.py
> +new_dict = {tuple: ['1', '3', '6', '7', 'None', 'text', 'False', '2.42'], list: ['1', '3', '6', '7', 'None', 'text', 'False', '2.42', 'sdsdf', 'Таня', 'Ира', 'Аня', 'Соня', 'Вова'], dict: {'key1': '2
Под ключами 'tuple' и 'set' находятся не кортеж и множество, а и там и там - списки.

2024-08-10 14:17 UTC, eugene-okulik commented on homework/irina_konovalova/homework_4/dictionary.py
> +catch = my_dict.update({getCheck: input("Введите значение ключа: ")})
Результатом этого инпута будет строка, но в задании указано, что ключом должно быть `('i am a tuple',) ` - а это кортеж с одним элементом.

2024-08-10 14:17 UTC, eugene-okulik commented on homework/irina_konovalova/homework_4/dictionary.py
> +del my_list[list_del-1]
Здесь нужно удалять не ту запись которую укажет пользователь, а именно вторую. Это важно в этом задании.

2024-08-10 14:17 UTC, eugene-okulik commented on homework/irina_konovalova/homework_4/dictionary.py
> +catch = my_dict.update({getCheck: input("Введите значение ключа: ")})
Намного понятнее будет, если ты руками будешь выполнять это задание, не спрашивая у пользователя что куда ввести. Ну, или нужно правильно преобразовать то, что ввел пользователь.

2024-08-13 10:40 UTC, eugene-okulik requested changes
В целом, из-за того, что в задании выполнено еще очень много лишнего, достаточно сложно понять что где. И хорошо бы исправлять то, о чем я пишу. Если не понятно как исправить, спрашивай.

2024-08-13 10:40 UTC, eugene-okulik commented on homework/irina_konovalova/homework_4/dictionary.py
> +new_dict['my_set'] = new_dict.pop(set)
Нужно было создать словарь с ключами ‘tuple’, ‘list’, ‘dict’, ‘set’, а не ‘my_tuple’, ‘my_list’, ‘my_dict’, ‘my_set’

2024-08-13 10:40 UTC, eugene-okulik commented on homework/irina_konovalova/homework_4/dictionary.py
> +my_dict[check] = " "
Результатом этого инпута будет строка, но в задании указано, что ключом должно быть ('i am a tuple',)  - а это кортеж с одним элементом.  
И я уже об этом тебе писал.

2024-08-13 10:40 UTC, eugene-okulik commented on homework/irina_konovalova/homework_4/dictionary.py
> +new_dict = {tuple: (1, 3, 6, 7, 'None', 'text', 'False', 2.42), list: ['1', '3', '6', '7', 'None', 'text', 'False', '2.42', 'sdsdf', 'Таня', 'Ира', 'Аня', 'Соня', 'Вова'], dict: {'key1':'22', 'key2':
Здесь ты создала словарь, клочами которого являются классы данных. Так никогда не делают, как минимум - нет смысла классы данных делать ключами.

2024-08-13 10:40 UTC, eugene-okulik commented on homework/irina_konovalova/homework_4/dictionary.py
> +new_dict['my_set'] = new_dict.pop(set)
И в целом, ты сначала сделала неправильный словарь, а потом переделала его в правильный. Нужно сразу сделать правильный.

2024-08-15 14:38 UTC, eugene-okulik requested changes
Нужно сделать, чтобы там, где указано какой ключ ввести, был введен именно такой ключ.  
И нужно поправить всё, на что ругается Lint

2024-08-15 14:38 UTC, eugene-okulik commented on homework/irina_konovalova/homework_4/dictionary.py
> +dict[check] = " "
Ключом всё еще является строка `'i am a tuple'`, а должен быть кортеж с одним элементом `('i am a tuple',)`

2024-08-19 03:13 UTC, iskonov commented on homework/irina_konovalova/homework_4/dictionary.py
> +dict[check] = " "
Здравствуйте!
В Вашем задании написано так: 
"Для того, что хранится под ключом ‘dict’:
добавьте элемент с ключом ('i am a tuple',) и любым значением
удалите какой-нибудь элемент".
Я добавила ключ 'i am a tuple', значение: " ". 
Результат выполнения:

********** Dict **********
{'key1': '22', 'key2': '23', 'key3': '147', 'key4': '1', 'key5': '-2'}
Добавлен ключ 'i am a tuple':  {'key1': '22', 'key2': '23', 'key3': '147', 'key4': '1', 'key5': '-2', 'i am a tuple': ' '}
Удален один элемент  {'key1': '22', 'key2': '23', 'key3': '147', 'key5': '-2', 'i am a tuple': ' '}

2024-08-19 03:17 UTC, iskonov commented on homework/irina_konovalova/homework_4/dictionary.py
> +new_dict = {tuple: ['1', '3', '6', '7', 'None', 'text', 'False', '2.42'], list: ['1', '3', '6', '7', 'None', 'text', 'False', '2.42', 'sdsdf', 'Таня', 'Ира', 'Аня', 'Соня', 'Вова'], dict: {'key1': '2
Сейчас правильно?:
{'tuple': (1, 3, 6, 7, None, 'text', False, 2.42), 'list': [1, 6, 7, None, 'text', False, 2.42, 'sdsdf', 'Ира', 'Вова', 'aaa'], 'dict': {'key1': '22', 'key2': '23', 'key3': '147', 'key5': '-2', 'i am a tuple': ' '}, 'set': {'12', 'width', '18/8/2024', '54', 'long', 'wide'}}

2024-08-19 03:19 UTC, iskonov commented on homework/irina_konovalova/homework_4/dictionary.py
> +catch = my_dict.update({getCheck: input("Введите значение ключа: ")})
Задание:
Для того, что хранится под ключом ‘dict’:
добавьте элемент с ключом ('i am a tuple',) и любым значением
удалите какой-нибудь элемент.
Выполнение:
********** Dict **********
{'key1': '22', 'key2': '23', 'key3': '147', 'key4': '1', 'key5': '-2'}
Добавлен ключ 'i am a tuple':  {'key1': '22', 'key2': '23', 'key3': '147', 'key4': '1', 'key5': '-2', 'i am a tuple': ' '}
Удален один элемент  {'key1': '22', 'key2': '23', 'key3': '147', 'key5': '-2', 'i am a tuple': ' '}

2024-08-19 03:21 UTC, iskonov commented on homework/irina_konovalova/homework_4/dictionary.py
> +del my_list[list_del-1]
Выполнение без input:
********** List **********
[1, 3, 6, 7, None, 'text', False, 2.42, 'sdsdf', 'Ира', 'Вова', 'aaa']
[1, 6, 7, None, 'text', False, 2.42, 'sdsdf', 'Ира', 'Вова', 'aaa']

2024-08-19 03:43 UTC, iskonov commented on homework/irina_konovalova/homework_4/dictionary.py
> +new_dict['my_set'] = new_dict.pop(set)
Исправила обьявление словаря:
new_dict = dict()

2024-08-19 03:48 UTC, iskonov commented on homework/irina_konovalova/homework_4/dictionary.py
> +my_dict[check] = " "
Вот такое задание есть:
"Для того, что хранится под ключом ‘dict’:
добавьте элемент с ключом ('i am a tuple',) и любым значением"
Я добавила:
********** Dict **********
{'key1': '22', 'key2': '23', 'key3': '147', 'key4': '1', 'key5': '-2'}
Добавлен ключ 'i am a tuple':  {'key1': '22', 'key2': '23', 'key3': '147', 'key4': '1', 'key5': '-2', 'i am a tuple': ' '}

2024-08-19 03:48 UTC, iskonov commented on homework/irina_konovalova/homework_4/dictionary.py
> +new_dict = {tuple: (1, 3, 6, 7, 'None', 'text', 'False', 2.42), list: ['1', '3', '6', '7', 'None', 'text', 'False', '2.42', 'sdsdf', 'Таня', 'Ира', 'Аня', 'Соня', 'Вова'], dict: {'key1':'22', 'key2':
Исправила это.

2024-08-19 09:52 UTC, eugene-okulik requested changes

2024-08-19 09:52 UTC, eugene-okulik commented on homework/irina_konovalova/homework_4/dictionary.py
> +dict[check] = " "
> Я добавила ключ 'i am a tuple', значение: " ".

В том и дело. Нужно добавить не ключ 'i am a tuple', а ключ ('i am a tuple',)  
Тот, ключ, который у тебя - строка  
Тот ключ, который нужно добавить - кортеж с одним элементом.

2024-08-20 07:37 UTC, eugene-okulik requested changes

2024-08-20 07:37 UTC, eugene-okulik commented on homework/irina_konovalova/homework_4/dictionary.py
> +dict.setdefault(check,(my_tuple_add))
Здесь setdefault не нужен. Ты добавила значение - кортеж с тремя элементами. Значение в этом задании не важно, в этом задании важен именно ключ. Сейчас ключ `'i am a tuple'` - строка. А должен быть ключ `('i am a tuple',)` - кортеж с одним значением.

2024-08-22 22:42 UTC, iskonov commented on homework/irina_konovalova/homework_4/dictionary.py
> +dict.setdefault(check,(my_tuple_add))
Евгений, здравствуйте! 
К сожалению, я не знаю, как выполнить это требование и задание, соответственно.
Что делать я не знаю.
Спасибо, Ирина.

2024-08-23 09:14 UTC, eugene-okulik commented on homework/irina_konovalova/homework_4/dictionary.py
> +dict.setdefault(check,(my_tuple_add))
Так ведь просто всё. Смотри, я вот тебе пишу, что ключ у тебя 'i am a tuple' - и это строка. А должно быть ('i am a tuple',) - и это кортеж с одним значением. Просто берешь, копируешь то, что я написал и используешь в коде  
вместо
```python
check = 'i am a tuple'
```
делаешь
```python
check = ('i am a tuple',)
```
И всё. Ты, похоже, где-то попыталась найти какой-то скрытый смысл и не смогла его найти, так как его нет )))

2024-08-23 09:14 UTC, eugene-okulik commented on homework/irina_konovalova/homework_4/dictionary.py
> +dict.setdefault(check,(my_tuple_add))
Это задание сделано специально, чтобы подчеркнуть то, что я рассказывал в видео: кортеж может быть ключом словаря и кортеж с одним элементом выглядит вот так.

2024-08-26 16:55 UTC, iskonov commented
Спасибо, Евгений, за Вашу подсказку.
Вроде, исправила.

2024-08-26 18:54 UTC, eugene-okulik approved these changes

2024-08-26 18:54 UTC, merged